### PR TITLE
MemcachedClientCache Rework

### PR DESCRIPTION
**Pull request by tgrassau**
I reworked MemcachedClientCache. The pull request includes the following changes 
- Only the methods defined in ICacheClient and IMemcachedClient are realized (all others have been deleted)
- I introduced a value wrapper class as the underlying library expects serializable types
- The implmentation uses ServiceStack 3.9 and Enyim.Caching 2.11 (latest binary version available in NuGet)

### CODE REVIEW

**Comment by mythz** [comment]
Awesome thx! 
I'll push a new version to NuGet on the weekend.

**Comment by mythz** [comment]
Hit Thomas,

I've just published the latest Memcached client on NuGet, which now uses the EnyimMemcached dependency on NuGet (instead of bundling it in). But I don't have memcached installed anywhere to be able to test it.

Can you do a spot check and let me know if the NuGet client works?
https://nuget.org/packages/ServiceStack.Caching.Memcached/3.9.2

Thx!

**Comment by tgrassau** [comment]
Hi Demis! I just tried it and it did work without any problems.

**Comment by mythz** [comment]
Awesome, I just announced it on twitter: https://twitter.com/ServiceStack/status/230334363924037633
Also I wrote a little something about the [ForeignKey] Attribute on OrmLite's home page:
https://github.com/ServiceStack/ServiceStack.OrmLite#new-foreign-key-attribute-for-referential-actions-on-updatedeletes

Feel free to make any updates to it as you see fit.

Thx!

**Pull request merged**
