### PR TITLE
Added Support for Ravendb Multi- Tenancy cases

### PR DESCRIPTION
**Pull request by lafama**
You guys are doing amazing work, however based on my understanding of Ravendb works i thought the following modifications to support both default and multi- tenancy databases scenarios would be of great importance.

### CODE REVIEW

**Comment by mythz** [comment]
Great, can you approve the [Contributor License Agreement](https://docs.google.com/forms/d/16Op0fmKaqYtxGL4sg7w_g-cXXyCoWjzppgkuqzOeKyk/viewform) so we can look at merging this in, thx.

**Comment by lafama** [comment]
Done

**Comment by mythz** [comment]
Great, thx :+1:

**Comment by lafama** [comment]
When  are this changes going to be available on nuget?

**Comment by mythz** [comment]
I'm looking at deploying a new v3 release tomorrow, in order to make it to v3 it needs to added to the **v3-fixes** branch. I've tried cherry-picking but it can't be merged cleanly, so can I get you to send a new pull-request for the **v3-fixes** branch? 

The [Contributing Wiki](https://github.com/ServiceStack/ServiceStack/wiki/Contributing) may have info that can help with this.

**Comment by lafama** [comment]
Whats up this ConvertTo method. In v3-fixes branch am getting this Error
-- No overload for method 'ConvertTo' takes 0 arguments

**Comment by lafama** [comment]
here: authSession.ConvertTo<UserAuth>(); has a compile error.
Should i still submit the pull request ?

**Comment by mythz** [comment]
`ConvertTo` is the new name for `TranslateTo`, which you can use instead. 
Give it another go, if you hit another snag, I'll have a go at manually merging it.

**Pull request merged**
